Image-Sharer/config/routes.rb
Rails.application.routes.draw do

  root 'images#index'

  resources :images do
    member do
      get 'share'
      post 'send_email'
    end
  end

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :likes, only: [:create, :destroy]
end

Image-Sharer/app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_many :likes, through: :user
  before_destroy :remove_likes
  validates :title, presence: { message: "Image Name can't be blank" }
  validates :url, presence: { message: "Image URL can't be blank" },
                  format: { with: %r{(http)s?(:)\/\/.[\S]+[.](png|jpeg|jpg|gif|tiff|bmp)},
                            message: 'Image URL is invalid' }
  validates :tag_list, presence: { message: 'Image needs to have at least one tag' },
                       length: { maximum: 50, message: 'Too many tags' }
  validate :maximum_tag_length
  acts_as_ordered_taggable

  def add_user_association(user_id)
    build_user(id: user_id)
  end

  private

  def maximum_tag_length
    tag_list.each do |tag|
      errors[:tag_list] << "Tag - #{tag} is longer than 30 characters" if tag.length > 30
    end
  end

  def remove_likes
    Like.find_by(image_id: id).try(:destroy)
  end
end

Image-Sharer/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :user_authenticated?, except: [:index, :show]

  def index
    if params.key?(:tag)
      display_tagged_images
    else
      @images = Image.order(created_at: :desc)
    end
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_permit_params)
    @image.add_user_association(session[:user_id])
    if !@image.save
      render :new, status: :unprocessable_entity
    else
      flash[:success] = 'Image uploaded successfully'
      redirect_to @image
    end
  end

  def show
    check_image_exists('view')
  end

  def edit
    check_image_exists('edit')
    authorize(@image)
  end

  def update
    @image = Image.find(params[:id])
    authorize(@image)
    if @image.update_attributes(image_edit_permit_params)
      redirect_to @image, flash: { success: 'Image Attributes changed successfully' }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    check_image_exists('delete')
    return unless @image.present?
    authorize(@image)
    @image.destroy!
    flash[:success] = 'You have successfully deleted the image'
    redirect_to root_path
  end

  def share
    check_image_exists('share')
    return unless @image.present?
    @share_form = ShareForm.new
    render partial: 'modals/form_modal'
  end

  def send_email
    check_image_exists('share')
    return unless @image.present?
    @share_form = ShareForm.new(share_form_permit_params)
    if @share_form.valid?
      @email = params[:share_form][:email]
      @message = params[:share_form][:message]
      prepare_mail
    else
      respond_to do |format|
        format.json do
          render partial: 'modals/form_modal.html.erb', status: :unprocessable_entity
        end
      end
    end
  end

  private

  def image_permit_params
    params.require(:image).permit(:title, :url, :tag_list)
  end

  def share_form_permit_params
    params.require(:share_form).permit(:email, :message)
  end

  def image_edit_permit_params
    params.require(:image).permit(:title, :tag_list)
  end

  def display_tagged_images
    if params[:tag].present?
      display_tag_present_message
    else
      flash.now[:danger] = 'Tag cannot be empty'
    end
  end

  def display_tag_present_message
    if Image.tagged_with(params[:tag]).present?
      @images = Image.tagged_with(params[:tag]).order(created_at: :desc)
    else
      flash.now[:danger] = "No images exist with tag - #{params[:tag]}"
    end
  end

  def prepare_mail
    begin
      image = Image.find(params[:id])
      @mail = ImageMailer.share_image(@email, @message, image.url)
        .deliver_now
      add_flash_message
    rescue ActiveRecord::RecordNotFound
      flash.now[:danger] = 'Oops.. Image you are trying to share does not exist'
      return render json: { flash: { danger: flash.now[:danger] }, url: root_url }, status: :not_found
    end
    render json: { flash: { success: flash.now[:success] }, url: root_url }
  end

  def add_flash_message
    if @mail.blank?
      flash.now[:danger] = 'Image could not be shared'
    else
      flash.now[:success] = "Image shared with #{params[:share_form][:email]}"
    end
  end

  def check_image_exists(message)
    @image = Image.find_by(id: params[:id])
    if @image.blank?
      error_message = "Oops.. Image you are trying to #{message} does not exist"
      respond_to do |format|
        format.json do
          flash.now[:danger] = error_message
          return render json: { flash: { danger: flash.now[:danger] } }, status: :not_found
        end
        format.html do
          flash[:danger] = error_message
          return redirect_to root_url, status: :not_found
        end
      end
    end
  end

  def user_authenticated?
    unless logged_in?
      session[:redirect_url] = request.original_url
      redirect_to new_session_path, flash: { warning: 'You need to login' }
    end
  end
end

Image-Sharer/app/helpers/images_helper.rb
module ImagesHelper
end

Image-Sharer/app/views/images/_image.html.erb
<div class="col-4 mb-3">
  <div class="js-card-image card text-center">
    <div class="card-header"><%= image.title %></div>
        <div class="card-block">
          <%= link_to image_path(image), class: 'js-img-link' do %>
            <%= image_tag(image.url, class: 'card-img-bottom card-image') %>
          <% end %>
          <% if image.tag_list.present? %>
              <div class="js-image-tags card-text">
                <div class="text-capitalize">Tags</div>
                <% image.tag_list.each do |tag| %>
                    <%= link_to tag, images_path(tag: tag), class: 'btn btn-outline-success btn-sm card-tag' %>
                <% end %></div>
              <% if logged_in? && policy(image).edit? %>
                  <br/><%= link_to 'Edit Tags', edit_image_path(image.id), class: 'js-edit-tags btn btn-outline-info btn-sm' %>
              <% end %>
          <% end %>``
        </div>
    <% if logged_in? %>
      <div class="card-footer">
        <div class="row card-action">
          <div class="col-md-4"> <%= link_to 'Share', share_image_path(image), class: 'js-share btn btn-outline-primary btn-sm', remote: true, data: { toggle: 'modal', target: '#image_modal', 'image_id': image.id } %> </div>
          <div class="col-md-4">
            <% if @current_user.liked?(image.id) %>
                  <%= link_to 'Unlike', like_path(image, user_id: @current_user.id), class: 'js-unlike btn btn-outline-primary btn-sm', method: :delete %>
            <% else %>
                  <%= link_to 'Like' , likes_path(image_id: image.id, user_id: @current_user.id), class: 'js-like btn btn-outline-primary btn-sm', method: :post %>
            <% end %>
          </div>
          <% if policy(image).destroy? %>
              <div class="col-md-4"> <%= button_to 'Delete', image_path(image), method: :delete, data: { confirm: 'Do you want to delete this image?' }, class: 'js-delete btn btn-outline-danger btn-sm' %>  </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

Image-Sharer/app/views/images/edit.html.erb
<%= simple_form_for @image, url: image_path(@image.id), html: { class: 'test-edit-image-form text-center' }, method: :put do |f| %>
  <%= image_tag @image.url, class:'test-edit-image-img' %>
  <%= f.input :title, label: 'Image Name', input_html: { class: 'test-edit-image-title' } %>
  <%= f.input :tag_list, label: 'Image Tags', input_html: { value: @image.tag_list.join(', '), class: 'test-edit-image-tag-list' } %>
  <%= f.submit 'Update Image', class: 'test-image-edit-submit btn btn-outline-success' %>
<% end %>

Image-Sharer/app/views/images/index.html.erb
<% if flash[:danger].blank? %>
  <div class="js-images row">
    <%= render partial: 'images/image', collection: @images %>
  </div>
  <% content_for :javascript do %>
    <%= javascript_include_tag 'modal/main' %>
  <% end %>
  <%= render partial: 'modals/image_modal' %>
<% end %>

Image-Sharer/app/views/images/new.html.erb
<%= simple_form_for @image, url: images_path, html: { class: 'text-center' }, method: :post do |i| %>
    <%= i.input :title, label: 'Image Name' %><br/>
    <%= i.input :url, label: 'Image URL' %><br/>
    <%= i.input :tag_list, label: 'Image Tags', input_html: { value: @image.tag_list.to_s } %><br/>
    <%= i.submit 'Upload Image', class: 'btn btn-outline-success' %>
<% end %>

Image-Sharer/app/views/images/share.html.erb
 <%= simple_form_for @share_form, url: send_email_image_path(params[:id]), method: :post do |f| %>
    <%= hidden_field_tag 'id', params[:id] %>
    <div class="row">
      <div class="col md-6">
        <%= image_tag(Image.find(params[:id]).url, class:'js-image') %>
      </div>
      <div class="col md-6">
        <%= f.input :email, label: 'Email', placeholder: 'first.last@example.com', input_html: { class: 'js-email form-control' } %><br/>
        <%= f.input :message, label: 'Message', placeholder: 'Enter message here', input_html: { class: 'js-message form-control' } , required: false %><br/>
        <%= f.submit 'Send Email', class: 'btn btn-outline-primary' %>
      </div>
    </div>
<% end %>

Image-Sharer/app/views/images/show.html.erb
<%= render partial: 'images/image', object: @image, as: :image %>

<%= render partial: 'modals/image_modal' %>